# Generated by Django 5.1.4 on 2025-04-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlisting',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlisting',
            unique_together={('owner_id', 'listing_id')},
        ),
    ]
