# Generated by Django 5.1.4 on 2025-04-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlisting_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlisting',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlisting',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='watchlisting',
            unique_together=set(),
        ),
    ]
