# Generated by Django 5.1.4 on 2025-04-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_listing_id_watchlisting_listing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlisting',
            unique_together={('owner', 'listing')},
        ),
    ]
